# Generated by Django 5.1.3 on 2024-11-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_tbl_cart_tbl_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booktable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('people', models.IntegerField(blank=True, null=True)),
                ('bookingdate', models.DateField(blank=True, null=True)),
                ('bookingtime', models.TimeField(blank=True, null=True)),
                ('eventtype', models.TextField(max_length=100, null=True)),
                ('foodtype', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tbl_product',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
