# Generated by Django 5.1.3 on 2024-11-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_tbl_booktable_alter_tbl_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booktable',
            name='foodtype',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
